### PR TITLE
Allow multiple base packages.

### PR DESCRIPTION
**Pull request by jamgocoop**
I found a situation where multiple base packages are needed. I think this could be useful to others.

### CODE REVIEW

**Comment by ethlo** [comment]
Hi and thank you for you very much for your pull request! :)

I have some feedback:

- The current setting is basePackage, and thus changing it to basePackages breaks backwards-compatibility. Please leave the original property there and just add the one allowing multiple basePackages.

- Please remove changes that are only whitespace/formatting. They clutter your patch.

**Comment by jamgocoop** [comment]
Ok. You are right.

So, do you think **both parameters** can be present? Ex.:

```xml
<configuration>
	<basePackage>org.my.project</basePackage>
	<basePackages>
		<basePackage>org.my.otherprojectA</basePackage>
		<basePackage>org.my.otherprojectB</basePackage>
	</basePackages>
</configuration>
```
or **mutually exclusive**? Ex.:

only one package:

```xml
<configuration>
	<basePackage>org.my.project</basePackage>
</configuration>
```
many packages:

```xml
<configuration>
	<basePackages>
		<basePackage>org.my.project</basePackage>
		<basePackage>org.my.otherprojectA</basePackage>
		<basePackage>org.my.otherprojectB</basePackage>
	</basePackages>
</configuration>
```

I think the second choice is better. But then I must add the mutually exclusivity validation. I'm not an expert in maven plugins but I think is not possible to do that validation only with annotations parameters. So, i will investigate a bit to put that validation in the correct place.

**Comment by ethlo** [comment]
Yes, just have both options. I would just throw an error if you try to set both :)

**Comment by jamgocoop** [comment]
Done.

**Comment by ethlo** [comment]
Thank you! Will cut a release (very) soon.

**Comment by ethlo** [comment]
Closed in 2.7.0

**Pull request merged**
